### ISSUE TITLE
Error: Cannot find module '@/utils'

### ISSUE THREAD

**Issue by peijunlei** [volcengine/ve-tos-js-sdk#2]
使用：
let { TOS } = require('@volcengine/tos-sdk');

node_modules/@volcengine/tos-sdk/dist/tos.cjs.development.js
第18行报错：var utils = require('@/utils');
Error: Cannot find module '@/utils'
Require stack:
node_modules/@volcengine/tos-sdk/dist/tos.cjs.development.js

使用方法有问题吗？

**Comment by peijunlei** [comment]
ve-tos-js-sdk/src/methods/object/multipart/uploadPartCopy.ts
ve-tos-js-sdk/src/methods/object/copyObject.ts
大佬，是不是这两处的utils引入有问题导致。

**Comment by MoonBall** [comment]
fixed
