### ISSUE TITLE
依赖的 axios-miniprogram-adapter 中的 axios 版本有安全漏洞

### ISSUE THREAD

**Issue by theajack** [volcengine/ve-tos-js-sdk#3]
依赖的 axios-miniprogram-adapter 中的 axios 版本有安全漏洞

需要大于 >= 0.21.1

**Comment by su-chang** [comment]
我已经在 `axios-miniprogram-adapter` repo 中提 [PR #53](https://github.com/bigmeow/axios-miniprogram-adapter/pull/53) 升级 `axios` 版本，如果合并后，希望能在该 repo 中升级 `axios-miniprogram-adapter` 对应的版本。

CC @MoonBall

**Comment by Dxings** [comment]
感谢反馈🙏，问题已经在 2.6.0 修复
