### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by suxi** [volcengine/ve-tos-js-sdk#4]
node_modules/.pnpm/@volcengine+tos-sdk@2.5.2/node_modules/@volcengine/tos-sdk/dist/utils.d.ts:8:80 - error TS2314: Generic type 'CamelCasedPropertiesDeep' requires 1 type argument(s).

 8 export declare const convertUpperCamelCase2Normal: <T = unknown>(target: T) => CamelCasedPropertiesDeep<T, {
                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9     preserveConsecutiveUppercase: true;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 }>;

**Comment by zhaohuijun** [comment]
遇到了同样的问题。我感觉需要把package.json里面对type-fest的依赖从devDependencies移到dependencies。

**Comment by sunshinefish** [comment]
如果是 yarn 管理的话，可以先在 resolution里锁死相关版本绕过这个
 "resolutions": {
    "type-fest": "3.11.1"
  },

**Comment by sunshinefish** [comment]
fixed in 2.5.3
